export type Difficulty = "Easy" | "Medium" | "Hard";
export type PlayerStyle = "Melee" | "Ranged" | "Summoner" | "Spell";

export type PoeClass = {
  id: number;
  name: string;
  slug: string;
  description: string;
  styles: PlayerStyle[];
  decisionUse: string;
  avoidIf: string;
};

export type Skill = {
  id: number;
  name: string;
  slug: string;
  aliases?: string[];
  tags: string[];
  description: string;
  level_requirement: number;
  bestFor: string;
  decisionRule: string;
};

export type Build = {
  id: number;
  title: string;
  slug: string;
  class: string;
  playstyle: string;
  difficulty: Difficulty;
  content: string;
  searchIntent: string;
  promise: string;
  coreSkills: string[];
  goodFor: string[];
  notFor: string[];
  levelingPlan: string[];
};

export const classes: PoeClass[] = [
  {
    id: 1,
    name: "Witch",
    slug: "witch",
    description: "Minion and chaos-oriented class for safer beginner progression.",
    styles: ["Summoner", "Spell"],
    decisionUse: "Recommended for Summoner players who want allies to absorb pressure while learning bosses.",
    avoidIf: "Skip it if you want direct weapon impact and hate minion management.",
  },
  {
    id: 2,
    name: "Monk",
    slug: "monk",
    description: "Fast melee class built around movement, combos, and burst windows.",
    styles: ["Melee"],
    decisionUse: "Recommended for Melee players who want speed and active positioning.",
    avoidIf: "Skip it if you want low-input gameplay or slow tank pacing.",
  },
  {
    id: 3,
    name: "Mercenary",
    slug: "mercenary",
    description: "Crossbow class for ranged players who like tactical weapon rhythm.",
    styles: ["Ranged"],
    decisionUse: "Recommended for Ranged players who want crossbows, ammo-style choices, and spacing control.",
    avoidIf: "Skip it if reload rhythm or swapping tools feels annoying.",
  },
  {
    id: 4,
    name: "Ranger",
    slug: "ranger",
    description: "Bow class focused on mobility, range, and efficient campaign clearing.",
    styles: ["Ranged"],
    decisionUse: "Recommended for Ranged players who want a clear, familiar starter path.",
    avoidIf: "Skip it if you dislike fragile early characters or constant repositioning.",
  },
  {
    id: 5,
    name: "Warrior",
    slug: "warrior",
    description: "Heavy melee class for armor, shields, stuns, and deliberate attacks.",
    styles: ["Melee"],
    decisionUse: "Recommended for Melee players who want durability and heavier hits.",
    avoidIf: "Skip it if your priority is the fastest campaign speed.",
  },
  {
    id: 6,
    name: "Sorceress",
    slug: "sorceress",
    description: "Elemental caster class for spell damage, control, and scaling one spell package.",
    styles: ["Spell"],
    decisionUse: "Recommended for Spell players who want clear elemental damage and simple caster scaling.",
    avoidIf: "Skip it if you want weapon-first combat or very low mana pressure.",
  },
  {
    id: 7,
    name: "Huntress",
    slug: "huntress",
    description: "Spear class for players who want to mix melee, ranged throws, and movement.",
    styles: ["Melee", "Ranged"],
    decisionUse: "Recommended for players who want hit-and-run combat and can learn spacing.",
    avoidIf: "Skip it if you want the safest low-effort beginner route.",
  },
  {
    id: 8,
    name: "Druid",
    slug: "druid",
    description: "Hybrid class for nature-themed combat and flexible role switching.",
    styles: ["Melee", "Spell"],
    decisionUse: "Recommended for players who want a flexible class fantasy and can adapt as patches shift.",
    avoidIf: "Skip it if you want the most documented beginner route immediately.",
  },
];

type SkillSeed = {
  name: string;
  aliases?: string[];
  tags: string[];
  role: string;
  levelRequirement?: number;
};

type BuildSeed = {
  title: string;
  class: string;
  playstyle: string;
  difficulty: Difficulty;
  mainSkill: string;
  supportSkills: string[];
  searchIntent: string;
  goal: string;
  avoid: string;
};

function slugifySkillName(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function createExpandedSkill(seed: SkillSeed, id: number): Skill {
  const tagLabel = seed.tags.join(", ");

  return {
    id,
    name: seed.name,
    slug: slugifySkillName(seed.name),
    aliases: seed.aliases,
    tags: seed.tags,
    description: `${seed.name} is a POE2 ${tagLabel} skill option for ${seed.role}.`,
    level_requirement: seed.levelRequirement ?? 1,
    bestFor: `Players who need ${seed.role}.`,
    decisionRule: `Choose it when your build needs ${seed.role}; skip it if a simpler core skill already solves that job.`,
  };
}

function createExpandedBuild(seed: BuildSeed, id: number): Build {
  return {
    id,
    title: seed.title,
    slug: slugifySkillName(seed.title),
    class: seed.class,
    playstyle: seed.playstyle,
    difficulty: seed.difficulty,
    searchIntent: seed.searchIntent,
    promise: `A decision-first ${seed.playstyle.toLowerCase()} route for players who want ${seed.goal}.`,
    content: `${seed.title} is for players deciding whether ${seed.mainSkill} should be their main skill direction. Keep the first version narrow: one main skill, two support tools, and clear defensive priorities before chasing endgame scaling.`,
    coreSkills: [seed.mainSkill, ...seed.supportSkills],
    goodFor: [`Players who want ${seed.goal}`, `${seed.class} players comparing build directions`, "Searchers who need a fast starter decision"],
    notFor: [seed.avoid, "Players who want a full passive tree planner", "Players looking for exact patch-sensitive DPS math"],
    levelingPlan: [
      `Use ${seed.mainSkill} as the main identity before adding extra damage packages.`,
      `Add ${seed.supportSkills[0]} when clear, control, or boss pressure starts to fall behind.`,
      "Upgrade defenses whenever deaths cost more time than low damage does.",
    ],
  };
}

const expandedSkillSeeds: SkillSeed[] = [
  { name: "Disengage", tags: ["melee", "spear", "mobility"], role: "creating distance after close-range spear pressure" },
  { name: "Explosive Spear", tags: ["ranged", "spear", "area"], role: "adding spear-based area damage to a hybrid setup" },
  { name: "Lightning Rod", tags: ["ranged", "bow", "lightning"], role: "setting up lightning bow damage around a target area" },
  { name: "Twister", tags: ["ranged", "physical", "projectile"], role: "adding projectile coverage when packs spread out" },
  { name: "Whirlwind", tags: ["melee", "physical", "area"], role: "staying active in melee while hitting several enemies" },
  { name: "Whirling Slash", tags: ["melee", "spear", "area"], role: "turning spear melee into a wider clearing tool" },
  { name: "Frost Bomb", tags: ["spell", "cold", "exposure"], role: "supporting cold damage with delayed area pressure" },
  { name: "Ice Nova", tags: ["spell", "cold", "area"], role: "clearing enemies that surround a caster" },
  { name: "Unearth", tags: ["spell", "minion", "corpse"], role: "creating corpse or minion support for Witch routes" },
  { name: "Armour Piercing Rounds", tags: ["ranged", "crossbow", "physical"], role: "breaking through armored targets on Mercenary" },
  { name: "Frozen Locus", tags: ["melee", "cold", "control"], role: "adding cold control to close-range Monk play" },
  { name: "Furious Slam", tags: ["melee", "warrior", "slam"], role: "giving Warrior a direct slam option for early pressure" },
  { name: "Glacial Cascade", tags: ["spell", "cold", "area"], role: "using cold waves to control lanes and packs" },
  { name: "Lunar Assault", tags: ["melee", "werewolf", "mobility"], role: "supporting fast shapeshift melee engagement" },
  { name: "Permafrost Bolts", tags: ["ranged", "crossbow", "cold"], role: "adding cold control to crossbow gameplay" },
  { name: "Volcano", tags: ["spell", "fire", "area"], role: "creating fire area pressure for slower fights" },
  { name: "Cull The Weak", tags: ["melee", "execute", "physical"], role: "finishing weakened enemies during aggressive melee play" },
  { name: "Fangs of Frost", tags: ["melee", "cold", "strike"], role: "building a cold melee identity around strike damage" },
  { name: "Freezing Salvo", tags: ["ranged", "cold", "projectile"], role: "adding burst cold projectiles for freeze-focused setups" },
  { name: "Lightning Spear", tags: ["ranged", "spear", "lightning"], role: "adding ranged lightning damage to spear builds" },
  { name: "Rake", tags: ["melee", "spear", "bleed"], role: "using spear melee to apply bleed pressure" },
  { name: "Snipe", tags: ["ranged", "bow", "single-target"], role: "trading speed for aimed single-target damage" },
  { name: "Stormcaller Arrow", tags: ["ranged", "bow", "lightning"], role: "building a bow setup around delayed lightning hits" },
  { name: "Vine Arrow", tags: ["ranged", "bow", "chaos"], role: "controlling space with bow-based plant pressure" },
  { name: "Bone Cage", tags: ["spell", "physical", "control"], role: "protecting a caster by controlling nearby enemies" },
  { name: "Enfeeble", tags: ["spell", "curse", "defense"], role: "reducing enemy threat in dangerous fights" },
  { name: "Fireball", tags: ["spell", "fire", "projectile"], role: "starting a direct fire caster package" },
  { name: "Frost Darts", tags: ["spell", "cold", "projectile"], role: "adding repeatable cold projectile pressure" },
  { name: "Living Bomb", tags: ["spell", "fire", "area"], role: "using delayed explosions for pack damage" },
  { name: "Flash Grenade", tags: ["ranged", "grenade", "control"], role: "buying time when enemies close distance" },
  { name: "Incendiary Shot", tags: ["ranged", "crossbow", "fire"], role: "adding fire damage to crossbow shots" },
  { name: "Rolling Magma", tags: ["spell", "fire", "projectile"], role: "covering uneven packs with bouncing fire damage" },
  { name: "Wind Blast", tags: ["melee", "monk", "control"], role: "creating breathing room around a melee character" },
  { name: "Wing Blast", tags: ["melee", "shapeshift", "area"], role: "adding area pressure to shapeshift combat" },
  { name: "Armour Breaker", tags: ["melee", "warrior", "physical"], role: "setting up physical damage against tougher enemies" },
  { name: "Infernal Cry", tags: ["warcry", "fire", "melee"], role: "adding a warcry damage layer to melee clearing" },
  { name: "Shield Charge", tags: ["melee", "shield", "mobility"], role: "turning shield use into movement and impact" },
  { name: "Shockwave Totem", tags: ["totem", "physical", "area"], role: "placing physical area damage while repositioning" },
  { name: "Electrocuting Arrow", tags: ["ranged", "bow", "lightning"], role: "adding lightning control to bow gameplay" },
  { name: "Rapid Assault", tags: ["melee", "spear", "fast"], role: "raising spear tempo for aggressive players" },
  { name: "Spearfield", tags: ["ranged", "spear", "area"], role: "controlling an area with spear pressure" },
  { name: "Storm Lance", tags: ["ranged", "spear", "lightning"], role: "using spear skills for lightning-focused damage" },
  { name: "Toxic Growth", tags: ["ranged", "chaos", "plant"], role: "building poison or chaos pressure over an area" },
  { name: "Arc", tags: ["spell", "lightning", "clear"], role: "clearing chained enemies with simple lightning casting" },
  { name: "Bonestorm", tags: ["spell", "physical", "projectile"], role: "adding physical spell projectiles to Witch routes" },
  { name: "Ember Fusillade", tags: ["spell", "fire", "projectile"], role: "building burst fire projectile pressure" },
  { name: "Raise Zombie", tags: ["summoner", "witch", "minion"], role: "adding expendable minions to a corpse-based setup" },
  { name: "Devour", tags: ["spell", "corpse", "sustain"], role: "turning corpses into recovery or fight stability" },
  { name: "Fury of the Mountain", tags: ["melee", "bear", "slam"], role: "supporting bear shapeshift slam gameplay" },
  { name: "Galvanic Shards", tags: ["ranged", "crossbow", "lightning"], role: "giving Mercenary lightning-based pack coverage" },
  { name: "Ice Shards", tags: ["ranged", "crossbow", "cold"], role: "using crossbow cold damage for control and clear" },
  { name: "Tempest Flurry", tags: ["melee", "monk", "lightning"], role: "scaling fast lightning melee hits" },
  { name: "Thunderstorm", tags: ["spell", "lightning", "area"], role: "adding persistent lightning pressure to fights" },
  { name: "Vaulting Impact", tags: ["melee", "spear", "mobility"], role: "entering or escaping fights with spear impact" },
  { name: "Molten Blast", tags: ["melee", "warrior", "fire"], role: "adding fire projectiles to heavy melee gameplay" },
  { name: "Perfect Strike", tags: ["melee", "fire", "single-target"], role: "rewarding timing with stronger single-target melee hits" },
  { name: "Resonating Shield", tags: ["melee", "shield", "physical"], role: "turning shield commitment into sustained damage" },
  { name: "Blood Hunt", tags: ["melee", "spear", "bleed"], role: "leaning into bleed payoff on spear builds" },
  { name: "Gas Arrow", tags: ["ranged", "bow", "chaos"], role: "creating chaos zones for bow-based damage over time" },
  { name: "Glacial Lance", tags: ["ranged", "spear", "cold"], role: "adding cold spear damage for safer spacing" },
  { name: "Primal Strikes", tags: ["melee", "elemental", "sustained"], role: "supporting elemental melee setups" },
  { name: "Elemental Weakness", tags: ["spell", "curse", "elemental"], role: "amplifying elemental damage against harder targets" },
  { name: "Profane Ritual", tags: ["spell", "chaos", "corpse"], role: "using corpses to support chaos spell pressure" },
  { name: "Temporal Chains", tags: ["spell", "curse", "control"], role: "slowing enemies so safer builds can stabilize" },
  { name: "Vulnerability", tags: ["spell", "curse", "physical"], role: "supporting physical hit or bleed damage" },
  { name: "Artillery Ballista", tags: ["totem", "crossbow", "projectile"], role: "placing ranged support damage for Mercenary setups" },
  { name: "Cross Slash", tags: ["melee", "spear", "physical"], role: "adding direct physical spear damage" },
  { name: "Explosive Shot", tags: ["ranged", "crossbow", "fire"], role: "adding explosive fire impact to crossbow play" },
  { name: "Glacial Bolt", tags: ["ranged", "crossbow", "cold"], role: "creating cold crossbow control from range" },
  { name: "Siphoning Strike", tags: ["melee", "lightning", "monk"], role: "supporting lightning melee sustain and pressure" },
  {
    name: "Time of Need",
    aliases: ["迫切需要", "迫切时刻", "time of need poe2", "poe2 time of need", "poe 2 time of need", "poe2 迫切时刻"],
    tags: ["spirit", "buff", "recovery"],
    role: "adding recovery support for players who need more survival",
    levelRequirement: 37,
  },
];

const expandedBuildSeeds: BuildSeed[] = [
  {
    title: "POE2 Witch Chaos Leveling Build",
    class: "witch",
    playstyle: "Chaos spell leveling",
    difficulty: "Easy",
    mainSkill: "Essence Drain",
    supportSkills: ["Contagion", "Dark Effigy"],
    searchIntent: "poe2 witch chaos leveling build",
    goal: "safe chaos damage while moving",
    avoid: "Players who want direct weapon impact",
  },
  {
    title: "POE2 Witch Fire Minion Build",
    class: "witch",
    playstyle: "Fire minion clear",
    difficulty: "Easy",
    mainSkill: "Skeletal Arsonist",
    supportSkills: ["Skeletal Warrior", "Raise Spectre"],
    searchIntent: "poe2 witch fire minion build",
    goal: "minions with stronger pack clear",
    avoid: "Players who dislike summon management",
  },
  {
    title: "POE2 Witch Corpse Starter Build",
    class: "witch",
    playstyle: "Corpse spell setup",
    difficulty: "Medium",
    mainSkill: "Detonate Dead",
    supportSkills: ["Unearth", "Profane Ritual"],
    searchIntent: "poe2 corpse witch build",
    goal: "setup-based burst from corpses",
    avoid: "Players who want one-button damage",
  },
  {
    title: "POE2 Witch Curse Support Build",
    class: "witch",
    playstyle: "Curse control",
    difficulty: "Medium",
    mainSkill: "Enfeeble",
    supportSkills: ["Temporal Chains", "Vulnerability"],
    searchIntent: "poe2 witch curse build",
    goal: "safer fights through enemy control",
    avoid: "Players who only care about direct damage",
  },
  {
    title: "POE2 Witch Bone Spell Build",
    class: "witch",
    playstyle: "Physical spell pressure",
    difficulty: "Medium",
    mainSkill: "Bonestorm",
    supportSkills: ["Bone Cage", "Raise Zombie"],
    searchIntent: "poe2 witch bone spell build",
    goal: "physical spell pressure with defensive control",
    avoid: "Players who want the simplest minion starter",
  },
  {
    title: "POE2 Warrior Earthquake Leveling Build",
    class: "warrior",
    playstyle: "Slam area leveling",
    difficulty: "Easy",
    mainSkill: "Earthquake",
    supportSkills: ["Rolling Slam", "Armour Breaker"],
    searchIntent: "poe2 warrior earthquake build",
    goal: "heavy melee clearing without complex rotations",
    avoid: "Players who need fast movement speed",
  },
  {
    title: "POE2 Warrior Boneshatter Build",
    class: "warrior",
    playstyle: "Physical stun melee",
    difficulty: "Easy",
    mainSkill: "Boneshatter",
    supportSkills: ["Armour Breaker", "Infernal Cry"],
    searchIntent: "poe2 warrior boneshatter build",
    goal: "direct physical damage and stun pressure",
    avoid: "Players who dislike close-range trading",
  },
  {
    title: "POE2 Warrior Shield Leveling Build",
    class: "warrior",
    playstyle: "Shield melee",
    difficulty: "Medium",
    mainSkill: "Shield Charge",
    supportSkills: ["Resonating Shield", "Shockwave Totem"],
    searchIntent: "poe2 warrior shield build",
    goal: "more defense while staying melee-focused",
    avoid: "Players who want pure two-handed slam damage",
  },
  {
    title: "POE2 Warrior Fire Slam Build",
    class: "warrior",
    playstyle: "Fire slam melee",
    difficulty: "Medium",
    mainSkill: "Molten Blast",
    supportSkills: ["Infernal Cry", "Volcano"],
    searchIntent: "poe2 warrior fire slam build",
    goal: "heavy melee with fire area pressure",
    avoid: "Players who want a pure physical setup",
  },
  {
    title: "POE2 Warrior Totem Slam Build",
    class: "warrior",
    playstyle: "Totem assisted melee",
    difficulty: "Medium",
    mainSkill: "Shockwave Totem",
    supportSkills: ["Earthquake", "Rolling Slam"],
    searchIntent: "poe2 warrior totem build",
    goal: "extra placed damage while playing heavy melee",
    avoid: "Players who dislike placing support skills",
  },
  {
    title: "POE2 Mercenary Grenade Leveling Build",
    class: "mercenary",
    playstyle: "Grenade clear",
    difficulty: "Easy",
    mainSkill: "Explosive Grenade",
    supportSkills: ["Gas Grenade", "Flash Grenade"],
    searchIntent: "poe2 mercenary grenade build",
    goal: "area damage and space control",
    avoid: "Players who dislike delayed explosions",
  },
  {
    title: "POE2 Mercenary Lightning Crossbow Build",
    class: "mercenary",
    playstyle: "Lightning crossbow",
    difficulty: "Medium",
    mainSkill: "Galvanic Shards",
    supportSkills: ["Voltaic Grenade", "Rapid Shot"],
    searchIntent: "poe2 mercenary lightning build",
    goal: "ranged lightning coverage on crossbow",
    avoid: "Players who want a pure physical crossbow path",
  },
  {
    title: "POE2 Mercenary Cold Crossbow Build",
    class: "mercenary",
    playstyle: "Cold crossbow control",
    difficulty: "Medium",
    mainSkill: "Ice Shards",
    supportSkills: ["Permafrost Bolts", "Glacial Bolt"],
    searchIntent: "poe2 mercenary cold build",
    goal: "ranged control and safer kiting",
    avoid: "Players who only want explosive clear",
  },
  {
    title: "POE2 Mercenary High Velocity Boss Build",
    class: "mercenary",
    playstyle: "Boss-focused crossbow",
    difficulty: "Medium",
    mainSkill: "High Velocity Rounds",
    supportSkills: ["Armour Piercing Rounds", "Flash Grenade"],
    searchIntent: "poe2 mercenary boss build",
    goal: "single-target crossbow damage for rares and bosses",
    avoid: "Players who mainly need pack clear",
  },
  {
    title: "POE2 Mercenary Rapid Shot Build",
    class: "mercenary",
    playstyle: "Fast crossbow firing",
    difficulty: "Easy",
    mainSkill: "Rapid Shot",
    supportSkills: ["Fragmentation Rounds", "Explosive Shot"],
    searchIntent: "poe2 rapid shot mercenary build",
    goal: "faster ranged pacing with crossbows",
    avoid: "Players who prefer slow tactical shots",
  },
  {
    title: "POE2 Ranger Poison Arrow Build",
    class: "ranger",
    playstyle: "Poison bow",
    difficulty: "Easy",
    mainSkill: "Poisonburst Arrow",
    supportSkills: ["Vine Arrow", "Gas Arrow"],
    searchIntent: "poe2 ranger poison build",
    goal: "bow damage over time and safer movement",
    avoid: "Players who want instant lightning clear",
  },
  {
    title: "POE2 Ranger Lightning Bow Build",
    class: "ranger",
    playstyle: "Lightning bow clear",
    difficulty: "Easy",
    mainSkill: "Lightning Arrow",
    supportSkills: ["Lightning Rod", "Stormcaller Arrow"],
    searchIntent: "poe2 ranger lightning build",
    goal: "fast bow clearing through lightning skills",
    avoid: "Players who dislike fragile ranged gameplay",
  },
  {
    title: "POE2 Ranger Ice Shot Build",
    class: "ranger",
    playstyle: "Cold bow control",
    difficulty: "Medium",
    mainSkill: "Ice Shot",
    supportSkills: ["Escape Shot", "Rain of Arrows"],
    searchIntent: "poe2 ranger ice shot build",
    goal: "bow control with cold pressure",
    avoid: "Players who want the simplest lightning starter",
  },
  {
    title: "POE2 Ranger Rain of Arrows Build",
    class: "ranger",
    playstyle: "Bow area clear",
    difficulty: "Medium",
    mainSkill: "Rain of Arrows",
    supportSkills: ["Lightning Arrow", "Escape Shot"],
    searchIntent: "poe2 rain of arrows build",
    goal: "wider bow coverage for dense packs",
    avoid: "Players who only need single-target damage",
  },
  {
    title: "POE2 Ranger Snipe Boss Build",
    class: "ranger",
    playstyle: "Aimed bow single-target",
    difficulty: "Hard",
    mainSkill: "Snipe",
    supportSkills: ["Escape Shot", "Vine Arrow"],
    searchIntent: "poe2 ranger snipe build",
    goal: "aimed single-target bow damage",
    avoid: "Players who want low-input clearing",
  },
  {
    title: "POE2 Monk Lightning Staff Build",
    class: "monk",
    playstyle: "Lightning quarterstaff",
    difficulty: "Medium",
    mainSkill: "Charged Staff",
    supportSkills: ["Falling Thunder", "Tempest Bell"],
    searchIntent: "poe2 monk lightning build",
    goal: "active lightning melee scaling",
    avoid: "Players who want slow tank gameplay",
  },
  {
    title: "POE2 Monk Ice Strike Build",
    class: "monk",
    playstyle: "Cold melee control",
    difficulty: "Medium",
    mainSkill: "Ice Strike",
    supportSkills: ["Frozen Locus", "Fangs of Frost"],
    searchIntent: "poe2 monk ice strike build",
    goal: "melee combat with cold control",
    avoid: "Players who want pure lightning monk",
  },
  {
    title: "POE2 Monk Tempest Bell Build",
    class: "monk",
    playstyle: "Combo payoff melee",
    difficulty: "Medium",
    mainSkill: "Tempest Bell",
    supportSkills: ["Killing Palm", "Falling Thunder"],
    searchIntent: "poe2 tempest bell build",
    goal: "combo payoff windows and boss pressure",
    avoid: "Players who dislike timing-based melee",
  },
  {
    title: "POE2 Monk Palm Leveling Build",
    class: "monk",
    playstyle: "Palm finisher leveling",
    difficulty: "Medium",
    mainSkill: "Killing Palm",
    supportSkills: ["Staggering Palm", "Wind Blast"],
    searchIntent: "poe2 monk palm build",
    goal: "active finishers and close-range control",
    avoid: "Players who want one-button melee",
  },
  {
    title: "POE2 Monk Siphoning Strike Build",
    class: "monk",
    playstyle: "Lightning sustain melee",
    difficulty: "Hard",
    mainSkill: "Siphoning Strike",
    supportSkills: ["Tempest Flurry", "Charged Staff"],
    searchIntent: "poe2 siphoning strike build",
    goal: "lightning melee pressure with sustain decisions",
    avoid: "Players who want the easiest monk route",
  },
  {
    title: "POE2 Sorceress Fireball Build",
    class: "sorceress",
    playstyle: "Fire spell projectile",
    difficulty: "Easy",
    mainSkill: "Fireball",
    supportSkills: ["Flame Wall", "Ember Fusillade"],
    searchIntent: "poe2 sorceress fireball build",
    goal: "direct fire casting and simple scaling",
    avoid: "Players who want cold control",
  },
  {
    title: "POE2 Sorceress Frostbolt Build",
    class: "sorceress",
    playstyle: "Cold projectile caster",
    difficulty: "Easy",
    mainSkill: "Frostbolt",
    supportSkills: ["Ice Nova", "Frost Bomb"],
    searchIntent: "poe2 sorceress frostbolt build",
    goal: "safe cold casting and control",
    avoid: "Players who want lightning clear speed",
  },
  {
    title: "POE2 Sorceress Arc Build",
    class: "sorceress",
    playstyle: "Lightning chain caster",
    difficulty: "Easy",
    mainSkill: "Arc",
    supportSkills: ["Orb of Storms", "Thunderstorm"],
    searchIntent: "poe2 sorceress arc build",
    goal: "simple chained lightning damage",
    avoid: "Players who dislike mana pressure",
  },
  {
    title: "POE2 Sorceress Flame Wall Build",
    class: "sorceress",
    playstyle: "Fire support caster",
    difficulty: "Medium",
    mainSkill: "Flame Wall",
    supportSkills: ["Spark", "Rolling Magma"],
    searchIntent: "poe2 flame wall build",
    goal: "layered fire damage around another main skill",
    avoid: "Players who want one standalone damage button",
  },
  {
    title: "POE2 Sorceress Cold Control Build",
    class: "sorceress",
    playstyle: "Cold control caster",
    difficulty: "Medium",
    mainSkill: "Ice Nova",
    supportSkills: ["Frost Bomb", "Frostbolt"],
    searchIntent: "poe2 cold sorceress build",
    goal: "slowing fights down with cold skills",
    avoid: "Players who want fastest screen clear",
  },
  {
    title: "POE2 Huntress Lightning Spear Build",
    class: "huntress",
    playstyle: "Lightning spear",
    difficulty: "Medium",
    mainSkill: "Lightning Spear",
    supportSkills: ["Spearfield", "Vaulting Impact"],
    searchIntent: "poe2 huntress lightning spear build",
    goal: "ranged spear damage with mobility",
    avoid: "Players who want a pure bow class",
  },
  {
    title: "POE2 Huntress Bleed Spear Build",
    class: "huntress",
    playstyle: "Bleed spear",
    difficulty: "Medium",
    mainSkill: "Rake",
    supportSkills: ["Blood Hunt", "Cross Slash"],
    searchIntent: "poe2 huntress bleed build",
    goal: "bleed pressure through spear attacks",
    avoid: "Players who want instant elemental damage",
  },
  {
    title: "POE2 Huntress Spearfield Build",
    class: "huntress",
    playstyle: "Spear area control",
    difficulty: "Medium",
    mainSkill: "Spearfield",
    supportSkills: ["Explosive Spear", "Disengage"],
    searchIntent: "poe2 spearfield build",
    goal: "area control while keeping spear identity",
    avoid: "Players who want simple melee trading",
  },
  {
    title: "POE2 Huntress Cold Spear Build",
    class: "huntress",
    playstyle: "Cold spear control",
    difficulty: "Medium",
    mainSkill: "Glacial Lance",
    supportSkills: ["Freezing Salvo", "Disengage"],
    searchIntent: "poe2 huntress cold spear build",
    goal: "safer spear gameplay through cold control",
    avoid: "Players who want fire or lightning damage",
  },
  {
    title: "POE2 Huntress Mobility Spear Build",
    class: "huntress",
    playstyle: "Mobile spear leveling",
    difficulty: "Hard",
    mainSkill: "Vaulting Impact",
    supportSkills: ["Rapid Assault", "Disengage"],
    searchIntent: "poe2 huntress mobility build",
    goal: "high-movement spear combat",
    avoid: "Players who want stationary damage",
  },
  {
    title: "POE2 Druid Bear Slam Build",
    class: "druid",
    playstyle: "Bear slam",
    difficulty: "Medium",
    mainSkill: "Fury of the Mountain",
    supportSkills: ["Earthquake", "Volcano"],
    searchIntent: "poe2 druid bear build",
    goal: "heavy shapeshift melee pressure",
    avoid: "Players who want a pure caster route",
  },
  {
    title: "POE2 Druid Volcano Build",
    class: "druid",
    playstyle: "Fire area hybrid",
    difficulty: "Medium",
    mainSkill: "Volcano",
    supportSkills: ["Molten Blast", "Earthquake"],
    searchIntent: "poe2 druid volcano build",
    goal: "fire area pressure in a hybrid route",
    avoid: "Players who need the safest beginner guide",
  },
  {
    title: "POE2 Druid Cold Hybrid Build",
    class: "druid",
    playstyle: "Cold hybrid control",
    difficulty: "Medium",
    mainSkill: "Glacial Cascade",
    supportSkills: ["Frostbolt", "Ice Nova"],
    searchIntent: "poe2 druid cold build",
    goal: "cold control while staying flexible",
    avoid: "Players who want one fixed damage type",
  },
  {
    title: "POE2 Druid Werewolf Build",
    class: "druid",
    playstyle: "Werewolf melee",
    difficulty: "Hard",
    mainSkill: "Lunar Assault",
    supportSkills: ["Whirlwind", "Wing Blast"],
    searchIntent: "poe2 druid werewolf build",
    goal: "fast shapeshift melee fantasy",
    avoid: "Players who want the most documented starter",
  },
  {
    title: "POE2 Druid Elemental Hybrid Build",
    class: "druid",
    playstyle: "Elemental hybrid",
    difficulty: "Hard",
    mainSkill: "Primal Strikes",
    supportSkills: ["Volcano", "Glacial Cascade"],
    searchIntent: "poe2 druid elemental build",
    goal: "flexible elemental decisions across melee and spells",
    avoid: "Players who dislike hybrid gearing",
  },
  {
    title: "POE2 Beginner Ranged Starter Build",
    class: "ranger",
    playstyle: "Beginner ranged starter",
    difficulty: "Easy",
    mainSkill: "Lightning Arrow",
    supportSkills: ["Escape Shot", "Rain of Arrows"],
    searchIntent: "poe2 beginner ranged build",
    goal: "a simple ranged first character",
    avoid: "Players who want minions or heavy melee",
  },
  {
    title: "POE2 Beginner Melee Starter Build",
    class: "warrior",
    playstyle: "Beginner melee starter",
    difficulty: "Easy",
    mainSkill: "Rolling Slam",
    supportSkills: ["Boneshatter", "Earthquake"],
    searchIntent: "poe2 beginner melee build",
    goal: "a durable melee first character",
    avoid: "Players who want ranged safety",
  },
];

export const skills: Skill[] = [
  {
    id: 1,
    name: "Raise Spectre",
    slug: "raise-spectre",
    aliases: ["幽魂", "poe2 spectre", "poe2 幽魂"],
    tags: ["summoner", "witch", "safe"],
    description: "Summons captured monsters to fight for you.",
    level_requirement: 23,
    bestFor: "Witch players who want safer progression with minion pressure.",
    decisionRule: "Choose it when safety and passive damage matter more than direct control.",
  },
  {
    id: 2,
    name: "Skeletal Warrior",
    slug: "skeletal-warrior",
    tags: ["summoner", "witch", "beginner"],
    description: "Provides basic frontline minions for early campaign stability.",
    level_requirement: 1,
    bestFor: "New summoner players who need bodies between them and enemies.",
    decisionRule: "Choose it as a simple baseline before optimizing advanced minions.",
  },
  {
    id: 3,
    name: "Skeletal Sniper",
    slug: "skeletal-sniper",
    tags: ["summoner", "ranged", "witch"],
    description: "Adds ranged minion pressure to a summoner setup.",
    level_requirement: 1,
    bestFor: "Summoners who want damage while staying out of melee range.",
    decisionRule: "Choose it when your minion setup lacks safe ranged damage.",
  },
  {
    id: 4,
    name: "Skeletal Arsonist",
    slug: "skeletal-arsonist",
    tags: ["summoner", "fire", "clear"],
    description: "Adds fire-focused minion damage for clearing packs.",
    level_requirement: 7,
    bestFor: "Witch builds that need better early pack clearing.",
    decisionRule: "Choose it when your summons survive but clear too slowly.",
  },
  {
    id: 5,
    name: "Detonate Dead",
    slug: "detonate-dead",
    aliases: ["尸爆", "poe2 detonate dead", "流放之路2 尸爆"],
    tags: ["spell", "corpse", "burst"],
    description: "Turns corpses into damage, rewarding players who can manage setup.",
    level_requirement: 23,
    bestFor: "Spell players who like burst windows and corpse-based gameplay.",
    decisionRule: "Choose it when you are comfortable setting up damage instead of spamming one button.",
  },
  {
    id: 6,
    name: "Essence Drain",
    slug: "essence-drain",
    tags: ["spell", "chaos", "damage-over-time"],
    description: "Applies chaos damage over time for safer spell pacing.",
    level_requirement: 7,
    bestFor: "Players who want steady damage while moving.",
    decisionRule: "Choose it when boss uptime and survival matter more than burst.",
  },
  {
    id: 7,
    name: "Contagion",
    slug: "contagion",
    tags: ["spell", "chaos", "clear"],
    description: "Spreads chaos pressure through packs.",
    level_requirement: 1,
    bestFor: "Chaos spell starters that need better pack coverage.",
    decisionRule: "Choose it when single-target chaos damage needs a clear partner.",
  },
  {
    id: 8,
    name: "Dark Effigy",
    slug: "dark-effigy",
    tags: ["spell", "chaos", "totem"],
    description: "Creates a chaos-focused damage helper for controlled fights.",
    level_requirement: 32,
    bestFor: "Players who want extra damage while kiting.",
    decisionRule: "Choose it when you want a placed damage source for tougher encounters.",
  },
  {
    id: 9,
    name: "Tempest Bell",
    slug: "tempest-bell",
    tags: ["melee", "monk", "bossing"],
    description: "A combo payoff skill that rewards active Monk play.",
    level_requirement: 7,
    bestFor: "Monk leveling builds that need single-target burst.",
    decisionRule: "Choose it when you like building pressure before a payoff window.",
  },
  {
    id: 10,
    name: "Falling Thunder",
    slug: "falling-thunder",
    tags: ["melee", "lightning", "monk"],
    description: "Adds lightning damage to an aggressive melee route.",
    level_requirement: 1,
    bestFor: "Monk players who want elemental melee from the start.",
    decisionRule: "Choose it when your melee plan needs early lightning identity.",
  },
  {
    id: 11,
    name: "Ice Strike",
    slug: "ice-strike",
    tags: ["melee", "cold", "control"],
    description: "A cold melee option that helps control enemies.",
    level_requirement: 15,
    bestFor: "Melee players who want more safety through chill and freeze pressure.",
    decisionRule: "Choose it when control matters more than pure speed.",
  },
  {
    id: 12,
    name: "Killing Palm",
    slug: "killing-palm",
    aliases: ["杀戮之掌", "poe2 killing palm", "poe 2 killing palm", "poe 2 杀戮之掌", "killing palm 杀戮之掌"],
    tags: ["melee", "monk", "execute"],
    description: "A finishing tool for active melee players.",
    level_requirement: 1,
    bestFor: "Monk players who like weaving execution tools into combat.",
    decisionRule: "Choose it when you enjoy watching enemy state and timing finishers.",
  },
  {
    id: 13,
    name: "Staggering Palm",
    slug: "staggering-palm",
    aliases: ["震荡掌", "staggering palm 震荡掌", "poe2 staggering palm", "poe 2 staggering palm"],
    tags: ["melee", "monk", "stun"],
    description: "Adds stagger pressure to close-range combat.",
    level_requirement: 7,
    bestFor: "Melee players who need more control over rares and bosses.",
    decisionRule: "Choose it when enemies are surviving long enough to punish you.",
  },
  {
    id: 14,
    name: "Charged Staff",
    slug: "charged-staff",
    tags: ["melee", "lightning", "monk"],
    description: "Supports a lightning quarterstaff playstyle.",
    level_requirement: 32,
    bestFor: "Monk builds committed to lightning scaling.",
    decisionRule: "Choose it when your build already has lightning support and staff uptime.",
  },
  {
    id: 15,
    name: "Fragmentation Rounds",
    slug: "fragmentation-rounds",
    tags: ["ranged", "crossbow", "mercenary"],
    description: "A straightforward crossbow clear tool.",
    level_requirement: 1,
    bestFor: "Mercenary starters that need an easy early clear button.",
    decisionRule: "Choose it when ranged comfort matters before advanced ammo swaps.",
  },
  {
    id: 16,
    name: "Explosive Grenade",
    slug: "explosive-grenade",
    tags: ["ranged", "grenade", "clear"],
    description: "Adds area damage to crossbow or grenade setups.",
    level_requirement: 1,
    bestFor: "Players who want slower but stronger pack explosions.",
    decisionRule: "Choose it when dense packs are your main slowdown.",
  },
  {
    id: 17,
    name: "Gas Grenade",
    slug: "gas-grenade",
    tags: ["ranged", "grenade", "damage-over-time"],
    description: "Creates lingering area pressure for controlled fights.",
    level_requirement: 15,
    bestFor: "Mercenary players who kite through damage zones.",
    decisionRule: "Choose it when you prefer controlling space over direct burst.",
  },
  {
    id: 18,
    name: "High Velocity Rounds",
    slug: "high-velocity-rounds",
    tags: ["ranged", "crossbow", "single-target"],
    description: "A focused crossbow option for tougher enemies.",
    level_requirement: 7,
    bestFor: "Mercenary builds that need a rare and boss damage button.",
    decisionRule: "Choose it when clear is fine but single-target feels weak.",
  },
  {
    id: 19,
    name: "Rapid Shot",
    slug: "rapid-shot",
    tags: ["ranged", "crossbow", "fast"],
    description: "A faster crossbow option for players who like steady fire.",
    level_requirement: 15,
    bestFor: "Ranged players who want less downtime between attacks.",
    decisionRule: "Choose it when crossbow pacing feels too slow.",
  },
  {
    id: 20,
    name: "Lightning Arrow",
    slug: "lightning-arrow",
    tags: ["ranged", "bow", "clear"],
    description: "A bow clear skill for fast ranged campaign play.",
    level_requirement: 1,
    bestFor: "Ranger players who want simple ranged clearing.",
    decisionRule: "Choose it when clearing packs quickly is more important than tanking.",
  },
  {
    id: 21,
    name: "Poisonburst Arrow",
    slug: "poisonburst-arrow",
    tags: ["ranged", "bow", "poison"],
    description: "A bow option for poison-oriented early damage.",
    level_requirement: 1,
    bestFor: "Ranger players who want damage over time instead of direct lightning clear.",
    decisionRule: "Choose it when you want poison identity from the first acts.",
  },
  {
    id: 22,
    name: "Escape Shot",
    slug: "escape-shot",
    tags: ["ranged", "bow", "mobility"],
    description: "Creates distance while attacking.",
    level_requirement: 1,
    bestFor: "Ranged players who keep dying when enemies close the gap.",
    decisionRule: "Choose it when survival depends on resetting distance.",
  },
  {
    id: 23,
    name: "Rain of Arrows",
    slug: "rain-of-arrows",
    tags: ["ranged", "bow", "area"],
    description: "Adds area coverage to a bow build.",
    level_requirement: 32,
    bestFor: "Bow builds that need stronger pack coverage later in campaign.",
    decisionRule: "Choose it when single arrows are no longer covering enough space.",
  },
  {
    id: 24,
    name: "Spark",
    slug: "spark",
    aliases: ["电火花", "poe 2 spark", "流放之路2 电火花"],
    tags: ["spell", "lightning", "clear"],
    description: "A lightning spell that covers space and clears packs.",
    level_requirement: 1,
    bestFor: "Sorceress players who want an easy caster starting point.",
    decisionRule: "Choose it when you want a simple spell package to scale early.",
  },
  {
    id: 25,
    name: "Flame Wall",
    slug: "flame-wall",
    aliases: [
      "火焰之墙",
      "火焰墙",
      "火墙",
      "poe2 flame wall",
      "poe 2 flame wall",
      "flame wall poe 2",
      "flame wall poe2",
      "poe2 flamewall",
      "poe 2 flamewall",
      "poe2 火焰之墙",
      "流放之路2 火焰之墙",
      "火焰墙 poe 2",
      "火焰墙 poe2",
      "poe2 火墙",
    ],
    tags: ["spell", "fire", "support"],
    description: "Creates fire damage zones and supports projectile plans.",
    level_requirement: 1,
    bestFor: "Spell players who want extra damage without standing still.",
    decisionRule: "Choose it when a main skill needs a reliable damage layer.",
  },
  {
    id: 26,
    name: "Frostbolt",
    slug: "frostbolt",
    tags: ["spell", "cold", "projectile"],
    description: "A cold projectile spell for safe caster progression.",
    level_requirement: 7,
    bestFor: "Casters who want cold scaling and range.",
    decisionRule: "Choose it when you want simple cold damage before heavier setups.",
  },
  {
    id: 27,
    name: "Orb of Storms",
    slug: "orb-of-storms",
    tags: ["spell", "lightning", "area"],
    description: "Places a lightning area effect for repeated damage.",
    level_requirement: 7,
    bestFor: "Lightning casters who want extra damage while moving.",
    decisionRule: "Choose it when you need a placed skill to support your main cast.",
  },
  {
    id: 28,
    name: "Rolling Slam",
    slug: "rolling-slam",
    tags: ["melee", "warrior", "stun"],
    description: "A heavy melee option for early Warrior pacing.",
    level_requirement: 1,
    bestFor: "Warrior players who want weighty attacks and control.",
    decisionRule: "Choose it when stability and stagger matter more than speed.",
  },
  {
    id: 29,
    name: "Boneshatter",
    slug: "boneshatter",
    tags: ["melee", "warrior", "single-target"],
    description: "A melee attack for players who want heavy physical pressure.",
    level_requirement: 1,
    bestFor: "Warrior starters that need a direct damage anchor.",
    decisionRule: "Choose it when you want a simple melee damage plan.",
  },
  {
    id: 30,
    name: "Earthquake",
    slug: "earthquake",
    tags: ["melee", "warrior", "area"],
    description: "A slam skill that adds area damage to heavy melee.",
    level_requirement: 1,
    bestFor: "Warrior players who need better pack clearing.",
    decisionRule: "Choose it when your melee build handles bosses but clears packs slowly.",
  },
  ...expandedSkillSeeds.map((seed, index) => createExpandedSkill(seed, index + 31)),
];

export const builds: Build[] = [
  {
    id: 1,
    title: "POE2 Beginner Minion Witch Build",
    slug: "poe2-beginner-minion-witch-build",
    class: "witch",
    playstyle: "Safe summoner",
    difficulty: "Easy",
    searchIntent: "poe2 beginner build",
    promise: "A low-pressure starter route for players who want summons to create space while learning.",
    content:
      "Use minions as baseline damage, keep your own position safe, and upgrade survival before chasing perfect damage. This page is a decision guide, not a full endgame planner.",
    coreSkills: ["Skeletal Warrior", "Skeletal Sniper", "Raise Spectre"],
    goodFor: ["First POE2 character", "Boss learning", "Players who dislike melee risk"],
    notFor: ["Direct weapon damage", "Players who hate minion management"],
    levelingPlan: [
      "Prioritize minion count and survival before damage luxury.",
      "Keep one curse or direct damage button for rare monsters.",
      "Upgrade defenses whenever deaths slow the campaign more than damage does.",
    ],
  },
  {
    id: 2,
    title: "POE2 Monk Leveling Build",
    slug: "poe2-monk-leveling-build",
    class: "monk",
    playstyle: "Mobile melee combo",
    difficulty: "Medium",
    searchIntent: "poe2 monk leveling build",
    promise: "A fast leveling route for players who want active melee without getting lost in passive choices.",
    content:
      "Monk works best when the build has one clear skill, one single-target payoff, and enough mobility to avoid trading hits. Do not split upgrades across too many damage types early.",
    coreSkills: ["Falling Thunder", "Tempest Bell", "Killing Palm"],
    goodFor: ["Active players", "Fast campaign tempo", "Melee players who like movement"],
    notFor: ["Low-input gameplay", "Players who want to stand still and tank"],
    levelingPlan: [
      "Choose one main damage route and commit early.",
      "Use mobility to avoid boss mechanics instead of overbuilding damage first.",
      "Keep single-target damage updated so act bosses do not become walls.",
    ],
  },
  {
    id: 3,
    title: "POE2 Mercenary Crossbow Starter Build",
    slug: "poe2-mercenary-crossbow-starter-build",
    class: "mercenary",
    playstyle: "Ranged crossbow",
    difficulty: "Medium",
    searchIntent: "mercenary crossbow build poe2",
    promise: "A beginner-readable Mercenary crossbow starter for players choosing clear, single-target, and escape skills before adding extra tools.",
    content:
      "Mercenary is a good fit when you enjoy switching tools and controlling distance. For a first crossbow build, keep the setup simple: Fragmentation Rounds for packs, High Velocity Rounds for rare and boss damage, and Escape Shot before adding grenades.",
    coreSkills: ["Fragmentation Rounds", "High Velocity Rounds", "Escape Shot"],
    goodFor: ["Ranged players", "Players who like weapon feel", "Crossbow leveling with clear skill roles"],
    notFor: ["Players who dislike reload rhythm", "Pure spell casters", "Players who want the lowest-input beginner build"],
    levelingPlan: [
      "Use Fragmentation Rounds or another simple crossbow clear skill so normal packs do not slow the campaign.",
      "Keep crossbow upgrades current because weak weapons make both clear and boss damage feel worse.",
      "Add High Velocity Rounds before rare monsters and act bosses become time sinks.",
      "Use terrain, range, and Escape Shot instead of trading hits.",
      "Add grenade or control tools only after clear, single target, and escape already feel stable.",
    ],
  },
  {
    id: 4,
    title: "POE2 Ranger Lightning Arrow Starter Build",
    slug: "poe2-ranger-lightning-arrow-starter-build",
    class: "ranger",
    playstyle: "Fast bow clear",
    difficulty: "Easy",
    searchIntent: "poe2 ranger starter build",
    promise: "A clear-speed starter for players who want a familiar ranged campaign path.",
    content:
      "Ranger should stay simple in week one: one clear skill, one escape tool, and enough defense to keep repositioning from becoming panic movement.",
    coreSkills: ["Lightning Arrow", "Escape Shot", "Rain of Arrows"],
    goodFor: ["Bow players", "Fast campaign clearing", "Players who value distance"],
    notFor: ["Face-tanking", "Players who dislike movement-heavy defense"],
    levelingPlan: [
      "Use Lightning Arrow as the core clear identity.",
      "Keep an escape or mobility skill ready for close-range pressure.",
      "Upgrade bow damage before adding complicated secondary packages.",
    ],
  },
  {
    id: 5,
    title: "POE2 Warrior Slam Starter Build",
    slug: "poe2-warrior-slam-starter-build",
    class: "warrior",
    playstyle: "Durable slam melee",
    difficulty: "Easy",
    searchIntent: "poe2 warrior starter build",
    promise: "A slower but stable melee route for players who want heavy hits and simple priorities.",
    content:
      "Warrior is the easy recommendation when a player wants durability more than speed. Keep the plan direct: one slam for packs, one damage button for rares, and defenses first.",
    coreSkills: ["Rolling Slam", "Boneshatter", "Earthquake"],
    goodFor: ["Durable melee", "Players who like heavy attacks", "Simple gearing priorities"],
    notFor: ["Fastest leveling", "High-mobility combat"],
    levelingPlan: [
      "Use a slam skill to keep packs from surrounding you.",
      "Maintain weapon upgrades because slow attacks punish weak weapons.",
      "Take defensive upgrades early if boss deaths start costing time.",
    ],
  },
  {
    id: 6,
    title: "POE2 Sorceress Spark Starter Build",
    slug: "poe2-sorceress-spark-starter-build",
    class: "sorceress",
    playstyle: "Lightning spell clear",
    difficulty: "Easy",
    searchIntent: "poe2 sorceress starter build",
    promise: "A simple caster route for players who want one main spell package and clean scaling.",
    content:
      "Sorceress is the straightforward Spell answer: pick a main spell, add one support layer, and solve mana and defenses before trying multiple elements.",
    coreSkills: ["Spark", "Orb of Storms", "Flame Wall"],
    goodFor: ["Spell players", "Clean caster scaling", "Ranged clear"],
    notFor: ["Weapon-first combat", "Players who hate mana management"],
    levelingPlan: [
      "Use Spark as the main clear button.",
      "Add Orb of Storms when stationary damage helps boss or rare fights.",
      "Do not split too early across too many elements.",
    ],
  },
  {
    id: 7,
    title: "POE2 Huntress Spear Leveling Build",
    slug: "poe2-huntress-spear-leveling-build",
    class: "huntress",
    playstyle: "Hit-and-run spear",
    difficulty: "Medium",
    searchIntent: "poe2 huntress leveling build",
    promise: "A mobile hybrid route for players who want melee and ranged spear decisions.",
    content:
      "Huntress should be treated as a spacing class in the first week. The goal is not max DPS; it is deciding whether hit-and-run spear gameplay fits the player.",
    coreSkills: ["Spear Throw", "Spearfield", "Escape Shot"],
    goodFor: ["Players who like movement", "Hybrid melee/ranged combat", "Spear fantasy"],
    notFor: ["Safest beginner route", "Low-input play"],
    levelingPlan: [
      "Keep a ranged spear option for unsafe enemies.",
      "Use movement to choose when to trade hits.",
      "Avoid mixing too many damage packages before the core loop feels smooth.",
    ],
  },
  {
    id: 8,
    title: "POE2 Druid Hybrid Starter Build",
    slug: "poe2-druid-hybrid-starter-build",
    class: "druid",
    playstyle: "Hybrid melee spell",
    difficulty: "Medium",
    searchIntent: "poe2 druid starter build",
    promise: "A flexible starter for players who want a hybrid fantasy and accept patch-sensitive guidance.",
    content:
      "Druid belongs in the first-week platform as a decision page, not a deep planner. The page helps players decide if hybrid class fantasy is worth the extra uncertainty.",
    coreSkills: ["Frostbolt", "Earthquake", "Orb of Storms"],
    goodFor: ["Hybrid players", "Experimenters", "Returning players"],
    notFor: ["Players who need the most documented route", "Pure one-button starters"],
    levelingPlan: [
      "Pick either melee-first or spell-first for the first acts.",
      "Do not split gear priorities until the main loop is stable.",
      "Treat this as a flexible route and update it after search and patch data arrives.",
    ],
  },
  ...expandedBuildSeeds.map((seed, index) => createExpandedBuild(seed, index + 9)),
];

export function getClassBySlug(slug: string) {
  return classes.find((item) => item.slug === slug);
}

export function getSkillBySlug(slug: string) {
  return skills.find((item) => item.slug === slug);
}

export function getBuildBySlug(slug: string) {
  return builds.find((item) => item.slug === slug);
}

export function getBuildsForClass(classSlug: string) {
  return builds.filter((build) => build.class === classSlug);
}

export function getBuildForGenerator(classSlug: string, difficulty: Difficulty) {
  return (
    builds.find((build) => build.class === classSlug && build.difficulty === difficulty) ??
    builds.find((build) => build.class === classSlug) ??
    builds.find((build) => build.difficulty === difficulty) ??
    builds[0]
  );
}
